---
- name: Install Zabbix-Server
  hosts: zabbix-servers
 
  tasks:

  - name: Install packages 
    pkgng:
      name:
      - nginx-1.18.0_49,2
      - mysql57-server-5.7.33
      - zabbix52-server-5.2.5 
      - zabbix52-frontend-5.2.5
      - zabbix52-agent-5.2.5
      - py37-pymysql-0.10.1
      state: present
     
  - name: Start and enable mysql
    service:
      name: mysql-server
      enabled: yes
      state: started

  - name: Check my.cnf
    stat:
      path: /root/.my.cnf
    register: check_my

  - name: Reset root password with .my.cnf
    mysql_user:
      name: root
      password: "{{ mysql_root_password }}"
      config_file: ~/.my.cnf
    when: check_my.stat.exists==True
 
  - name: Get first db pass
    shell:
      cmd: cat .mysql_secret | tail -n 1
    register: secret
    when: check_my.stat.exists==False
 
  - name: Reset tmp password without .my.cnf
    shell:
      cmd: mysql -e "SET PASSWORD = PASSWORD('{{ mysql_root_password }}');" --connect-expired-password -uroot -p"{{ secret.stdout }}"
    when: check_my.stat.exists==False
 
  - name: Copy my.cnf
    template:
      src: .my.cnf.j2
      dest: /root/.my.cnf
      owner: root
      mode: 0600
      force: yes

  - name: Create zabbix db 
    mysql_db:
      name: "{{ zabbix_database_name }}"
      encoding: utf8
      state: present 
      collation: utf8_bin
      
  - name: Create or change pass zabbix user
    mysql_user:
      name: "{{ zabbix_database_user }}"
      password: "{{ zabbix_database_password }}" 
      priv: "{{ zabbix_database_name }}.*:ALL"

  - name: Import database information to zabbix db
    mysql_db:
      login_user: "{{ zabbix_database_user }}" 
      login_password: "{{ zabbix_database_password }}"
      name: "{{ zabbix_database_name }}"
      target: /usr/local/share/zabbix52/server/database/mysql/{{ item }}
      state: import
      force: yes 
    loop:
    - schema.sql
    - images.sql
    - data.sql

  - name: Copy configs
    template:
      src: templates/{{ item }}.j2
      dest: /usr/local/etc/{{ item }}
    loop:
    - zabbix52/zabbix_server.conf
    - zabbix52/zabbix_agentd.conf
    - php.ini
    - nginx/nginx.conf
     
  - name: Give www permissions on zabbix web
    file:
      dest: /usr/local/www/zabbix52
      owner: www
      group: www
      recurse: yes 

  - name: Restart(or start) and enable zabbix server and agent
    service:
      name: "{{ item }}"
      enabled: yes
      state: restarted
    loop:  
    - zabbix_server
    - zabbix_agentd

  - name: Reload services(php-fpm, nginx)
    service:
      name: "{{ item }}"
      enabled: yes
      state: reloaded
    loop:
    - php-fpm
    - nginx
